name: Publish Wiki

on:
  push:
    branches: [master]
    paths:
      - 'docs/**'
      - '.github/workflows/publish-wiki.yaml'

concurrency:
  group: publish-wiki
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Get last two tags
        id: tags
        run: |
          if TAG1=$(git describe --tags --abbrev=0 2>/dev/null); then
            if TAG2=$(git describe --tags --abbrev=0 $TAG1^ 2>/dev/null); then
              echo "TAG1=$TAG1" >> $GITHUB_OUTPUT
              echo "TAG2=$TAG2" >> $GITHUB_OUTPUT
            else
              echo "TAG1=$TAG1" >> $GITHUB_OUTPUT
              echo "TAG2=initial" >> $GITHUB_OUTPUT
            fi
          else
            echo "TAG1=initial" >> $GITHUB_OUTPUT
            echo "TAG2=none" >> $GITHUB_OUTPUT
          fi
      
      - name: Update documentation with version info
        run: |
          sed -i "s/Current Version: .*/Current Version: ${{ steps.tags.outputs.TAG1 }}/" docs/Home.md
          sed -i "s/Previous Version: .*/Previous Version: ${{ steps.tags.outputs.TAG2 }}/" docs/Home.md
          if [ "${{ steps.tags.outputs.TAG2 }}" != "none" ] && [ "${{ steps.tags.outputs.TAG2 }}" != "initial" ]; then
            echo -e "\n## Changes between ${{ steps.tags.outputs.TAG2 }} and ${{ steps.tags.outputs.TAG1 }}\n" >> docs/Release-Notes.md
            git log --pretty=format:"- %s" ${{ steps.tags.outputs.TAG2 }}..${{ steps.tags.outputs.TAG1 }} >> docs/Release-Notes.md
          fi
      
      - name: Publish to Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          path: docs/
          commit-message: "docs: update documentation [automated]"
          strategy: clone
          repository: ${{ github.repository }}
          github-server-url: ${{ github.server_url }}
          token: ${{ github.token }}
          dry-run: false
